### ISSUE TITLE
Write the "life of a Fluentd event" page

### ISSUE THREAD

**Issue by kiyoto** [fluent/fluentd-docs#154]
In v0.12, the event routing mechanism has changed for Fluentd. It's a good opportunity to create a page that gives an overview of how events come into Fluentd, how it is routed, etc.

**Comment by edsiper** [comment]
Initial version of the article here: b19db2db4d67e05d59e54d5038bcaef2d3d4a829 . Comments are welcome, I am sure it can be improved.

**Comment by kiyoto** [comment]
Commented on b19db2d It looks like a really good first draft.

I will do my share and add a diagram once it is pushed to the live site.

**Comment by kiyoto** [comment]
@eduardo can you s/FluentD/Fluentd/? Then it's ready to be merged. Adding images should be the next step.

**Comment by edsiper** [comment]
ack

On Fri, Jan 30, 2015 at 3:01 PM, Kiyoto <notifications@github.com> wrote:

> @eduardo <https://github.com/eduardo> can you s/FluentD/Fluentd/? Then
> it's ready to be merged. Adding images should be the next step.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fluent/fluentd-docs/issues/154#issuecomment-72269571>.
>



-- 
Eduardo Silva
http://edsiper.linuxchile.cl
http://monkey-project.com

**Comment by kiyoto** [comment]
:+1:

**Comment by repeatedly** [comment]
This page is already available on docs.fluentd.org
