### ISSUE TITLE
Dead link in install-by-deb

### ISSUE THREAD

**Issue by dmikurube** [fluent/fluentd-docs#156]
A link "What are the differences between td-agent and Fluentd?" from "install-by-deb" is dead in Japanese version.

From 「Fluentdとtd-agentの違いは<<ここ>>で確認することができます。」 in http://docs.fluentd.org/ja/articles/install-by-deb, <<ここ>> points http://docs.fluentd.org/ja/articles/faq#what-is-the-difference-with-td-agent-and-fluentd whose #anchor is dead.

The English version points http://www.fluentd.org/faqs.

**Comment by kiyoto** [comment]
fixed with 0fd59318b7b48689463baacd99b0a75f82c368af Thanks!
