### ISSUE TITLE
correction on Installing Fluentd (td-agent) on heroku

### ISSUE THREAD

**Issue by kbowerma** [fluent/fluentd-docs#157]
From [this](http://docs.fluentd.org/articles/install-on-heroku) document you instruct the user to modify the config file and re-deploy to Heroku.   Although this will work, when you say 'modify' I think you are implying the user should add the api key.   Your config file reads the api key from the environmental variable so it would be better to set the key through the environmental variable than from a config.

It would be better if you told the user to:
1.   go to the heroku settings for the app  ```Reveal Config Vars ```
2.  Add the key  ```TREASURE_DATA_API_KEY``` with the appropriate value 

OR the user could simply run from the console:
```heroku config:set TREASURE_DATA_API_KEY=actualyKeyValue```

**Comment by kiyoto** [comment]
Thanks for the feedback. Indeed this doc is out of date in so many ways (We even actually have a Heroku button for td-agent -> https://github.com/treasure-data/heroku-td-agent)

Would you be willing to contribute a PR?

**Comment by kbowerma** [comment]
Sure but it will take some time.   Can I ask if a heroku-td-agent on node is in the works?

**Comment by kiyoto** [comment]
@kbowerma np. I will get to this tomorrow. many thanks for pointing it out =)

> Can I ask if a heroku-td-agent on node is in the works?

Can you elaborate? Do you mean an implementation in Node.js? There is a logger to Fluentd for Node.js -> https://github.com/fluent/fluent-logger-node (i.e., Node.js app -> Fluentd -> Treasure Data, etc.)

**Comment by kiyoto** [comment]
@kbowerma just updated. please take a look. actually, this was a BUG since the latest td-agent.conf template for Heroku used config var (as you pointed out) but the docs had a vague instruction to edit the config.

Thanks a bunch!
