### ISSUE TITLE
Example parser plugin naming ambiguity

### ISSUE THREAD

**Issue by jdrago999** [fluent/fluentd-docs#162]
If you read the examples here -- http://docs.fluentd.org/articles/plugin-development#parser-plugins -- you'll see that the plugin's class name is `TimeKeyValueParser`, it is registered with `Plugin.register_parser("time_key_value", self)` yet the article says you should update your td-agent config with:

```
# Other lines...
<source>
  type tail
  path /path/to/input/file
  format time_key_parser
</source>
```

Intuitively it makes sense that it would say `format time_key_value_parser` instead.

**Comment by repeatedly** [comment]
Thanks! Just fixed!

**Comment by jdrago999** [comment]
:+1:
