### ISSUE TITLE
Reorganization of directories

### ISSUE THREAD

**Issue by sonots** [fluent/fluentd-docs#173]
Since v0.12 is the master article currently, and `ja` is not supported anymore, the current directory organization looks wierd. 

```
docs/(v0.10 documents here)
docs/ja/(ja documents here)
docs/v0.12/(v0.12 documents here and this is the master)
```

I propose to reorganize directories like:

```
docs/(master branch documents?)
docs/v0.10/(v0.10 documents)
docs/v0.12/(v0.12 documents)
```

Files directly under docs directory would mean documents for the `master` branch (no gem is released yet). This may not be required.

**Comment by fujimotos** [comment]
I believe this "directory layout" issue is addressed by c6ec3df5017068589e15ebff6bcf97a8bf454ca0.

So I'll close this issue.
