### ISSUE TITLE
install by deb is insecure

### ISSUE THREAD

**Issue by fw42** [fluent/fluentd-docs#174]
http://docs.fluentd.org/articles/install-by-deb

This page advises users to fetch a shell script over http (unencrypted), which then installs a debian package which is signed by an untrusted gpg key (which is also fetched via http, unencrypted).

Both those things (fetching the script and fetching the key) should probably happen over https, otherwise this is vulnerable to MITM attacks.

**Comment by repeatedly** [comment]
Thanks for the report :+1: 
We will fix this issue soon!

**Comment by repeatedly** [comment]
Okay. We now use CloudFront's default certificate and it causes a warning for HTTPS access.
We will use our certificate instead of CloudFront's default.
Please wait...

**Comment by repeatedly** [comment]
We updated scripts to use HTTPS for GPG key.
After refreshed caches, it will be available.

Installation script itself needs an another setup.
Please wait a moment...

**Comment by repeatedly** [comment]
We are now contacting to fastly for enabling SSL.

**Comment by commanderrikker** [comment]
Is there any update on this?  Currently the installer for Trusty doesn't work as it points to a repo that apparently no longer exists:
  http://packages.treasuredata.com/2/ubuntu/trusty/

**Comment by repeatedly** [comment]
`curl -L https://td-toolbelt.herokuapp.com/sh/install-ubuntu-trusty-td-agent2.sh | sh` works for me.
Could you show me your logs?

Currently, td-agent repository is hosted on S3 so several directory paths are 404.
But files are exist > http://packages.treasuredata.com.s3.amazonaws.com/2/ubuntu/trusty/pool/contrib/t/td-agent/td-agent_2.2.0-0_amd64.deb

**Comment by commanderrikker** [comment]
Sure.  Here's what I'm doing.  

This page...
http://docs.fluentd.org/articles/install-by-deb

Gives this command to run on Ubuntu 14.04.
  curl -L https://td-toolbelt.herokuapp.com/sh/install-ubuntu-trusty-td-agent2.sh | sh

That shell script looks like this:
```
curl https://packages.treasuredata.com/GPG-KEY-td-agent | apt-key add -

  # add treasure data repository to apt
  echo "deb [arch=amd64] http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib" > /etc/apt/sources.list.d/treasure-data.list

  # update your sources
  apt-get update

  # install the toolbelt
  apt-get install -y --force-yes td-agent
```
It's that link that is being added as a repo that is dead.  Thus when I run the initial curl command to download and execute the script, I get a package not found error.

**Comment by repeatedly** [comment]
I close this issue. If someone hits another error, please open new issue.
