### ISSUE TITLE
"in_http" accepts "format json" but it's not listed

### ISSUE THREAD

**Issue by adamchainz** [fluent/fluentd-docs#178]
Pretty simple fix, can be added to the list in "ltsv, tsv, csv and none are also supported."

**Comment by kiyoto** [comment]
Do you want to send a PR? It's under `docs/in_http.txt`!

**Comment by adamchainz** [comment]
Added, but I'm not sure this is the only missing format that is supported - I can't easily trace the source in https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_http.rb which also seems to be checking for content-type
