### ISSUE TITLE
Ubuntu version code names mixed up

### ISSUE THREAD

**Issue by willylee** [fluent/fluentd-docs#181]
On page http://docs.fluentd.org/articles/install-by-deb,

"For Ubuntu, "14.04 LTS / Precise", "12.04 LTS / Lucid", "10.04 LTS / Lucid" are currently supported. " 

should read

"For Ubuntu, "14.04 LTS / Trusty", "12.04 LTS / Precise", "10.04 LTS / Lucid" are currently supported. "

**Comment by repeatedly** [comment]
Thanks!
