### ISSUE TITLE
http://docs.fluentd.org/articles/windows: Wrong configuration for nxlog

### ISSUE THREAD

**Issue by phuongnd08** [fluent/fluentd-docs#186]
The linux server is listening on 5140, yet the client is told to output data to localhost (wrong server) and 9200 (wrong port). Though I have no luck telling nxlog to connecting to linux.server:5140 neither.

**Comment by kiyoto** [comment]
Thanks. I fixed the doc.

>Though I have no luck telling nxlog to connecting to linux.server:5140 neither

This might be due to your outgoing firewall setting or your Linux machine's incoming firewall setting. Have you checked those?
