### ISSUE TITLE
Failing to convert words wrapped with single underscores

### ISSUE THREAD

**Issue by occho** [fluent/fluentd-docs#187]
The words `matching` in the following lines are rendered as "_match_ing".
I'm not sure whether this is what you expect or not, but if not, they should be something like `<em>match</em>ing`.

codes:
https://github.com/fluent/fluentd-docs/blob/master/docs/config-file.txt#L81
https://github.com/fluent/fluentd-docs/blob/master/docs/v0.12/config-file.txt#L82

web page: http://docs.fluentd.org/articles/config-file#2-ldquomatchrdquo-tell-fluentd-what-to-do

**Comment by repeatedly** [comment]
Thanks for pointing this out!
