### ISSUE TITLE
Use Cases/Log Management and Search - Kibana is now version 4

### ISSUE THREAD

**Issue by antho31** [fluent/fluentd-docs#189]
Kibana is different, now updated to 4.1
-> Download here : https://www.elastic.co/downloads/kibana
-> Extract archive 
-> Open config/kibana.yml in an editor and set the elasticsearch_url  if ElasticSearch is running on another machine (default : localhost) 
-> Run with ./bin/kibana 
-> Access to the Kibana interface with a browser : http://localhost:5601

**Comment by repeatedly** [comment]
Thanks!

@kiyoto Do you have a time to update this article?
