### ISSUE TITLE
Splunk-like Grep-and-Alert-Email System 

### ISSUE THREAD

**Issue by Amirioelmos** [fluent/fluentd-docs#191]
hello all

when i copy this part " Configuration File: Soup to Nuts "  and paste to my config fluent-ui not working.

?????

**Comment by repeatedly** [comment]
Sorry, there is less information.
What does 'not working' mean?
Could you paste your error log?

**Comment by Amirioelmos** [comment]
sorry:D
<store>
.
.
.
subject [URGENT] APACHE 5XX ERROR  
</store>

It is an error -> [URGENT]  , not arry of json, and fluentd dosnt parse this.

thanks.

**Comment by repeatedly** [comment]
This topic is discussed on ML so close this issue.
