### ISSUE TITLE
config.d read order

### ISSUE THREAD

**Issue by aj-jester** [fluent/fluentd-docs#192]
I think the doc should make it clear the order in which the files are read in `config.d`. Logic says alphabetical but I haven't gone through the codebase. If its not alphabetical how does the order get determined?

Thanks.

**Comment by repeatedly** [comment]
> the order in which the files are read in config.d

It means `@include` directive, right?

**Comment by aj-jester** [comment]
Well...so if I have something like `@include config.d/*.conf` and inside `config.d` dir I have `aaa.conf` and `bbb.conf`. While file is read first? `aaa.conf` or `bbb.conf`?

**Comment by repeatedly** [comment]
`aaa.conf` should be first.
But depends on it is bad approach. See https://github.com/fluent/fluentd/pull/266 comments.
Anyway, I will add a comment to `@include` section.

**Comment by repeatedly** [comment]
Pushed!

**Comment by aj-jester** [comment]
Thanks for updating the docs.
