### ISSUE TITLE
flush_interval default 60s is out of date.

### ISSUE THREAD

**Issue by hmatsuoka** [fluent/fluentd-docs#193]
According to the reference, flush_interval default is 60s.
http://docs.fluentd.org/articles/out_forward#flushinterval

Although flush_interval is set as default 300s on the source code.
http://docs.fluentd.org/articles/out_forward#flushinterval 

Could you please update the reference?

**Comment by repeatedly** [comment]
Which is one?
From the source code, flush_interval is 60.

https://github.com/fluent/fluentd/blob/c5290387ea57a606c4626ab6d6ad6eb91d9525aa/lib/fluent/output.rb#L183

**Comment by repeatedly** [comment]
Can I close?
