### ISSUE TITLE
Ubuntu install incorrect

### ISSUE THREAD

**Issue by qingchuwudi** [fluent/fluentd-docs#197]
fluentd doc http://docs.fluentd.org/articles/install-by-deb is   

    curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sh

I tried but failed , and http://docs.treasure-data.com/articles/installing-the-cli#ubuntu-amp-debian is  

    curl -L http://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sh

using http instead of https, this is ok.

**Comment by qingchuwudi** [comment]
add key if failed with the second command

    sudo apt-key adv --recv-keys --keyserver keyserver.Ubuntu.com  1093DB45A12E206F

**Comment by repeatedly** [comment]
This is not incorrect. If using https is failed, it seems your environment issue.
curl is old or certification issue?

> and http://docs.treasure-data.com/articles/installing-the-cli#ubuntu-amp-debian is

It seems outdated. Using http is insecure. We will update above document.

**Comment by repeatedly** [comment]
Updated docs.treasuredata.com article. Close.
