### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by milan-koudelka** [fluent/fluentd-docs#198]
Please add info if max_retrywait is in seconds. It probably is, but I'm not 100% sure.
http://docs.fluentd.org/articles/out_forward#retrywait-maxretrywait

**Comment by repeatedly** [comment]
What does 'max_retry_wait is in seconds' mean?

> The interval doubles (with +/-12.5% randomness) every retry until max_retry_wait is reached.

Above sentence is not clear?

**Comment by milan-koudelka** [comment]
I used that, so I know that it is  in seconds now. But it should be even in minutes. There is written that default is 1.0 (minutes/seconds) and doubled every retry.
I see that it is not specified usually on other parameter too. But there is at least some default in the correct units. Like "The default is 10 seconds."

**Comment by repeatedly** [comment]
I added. If you notice other un-clear parameters, please let me know.

**Comment by milan-koudelka** [comment]
Thx.
