### ISSUE TITLE
Mistake in overview example?

### ISSUE THREAD

**Issue by reinerRubin** [fluent/fluentd-docs#201]
[In filter plugin overview](http://docs.fluentd.org/articles/filter-plugin-overview) we have got:
```text
<filter foo.bar>
  type record_transformer
  <record>
    hostname ${Socket.gethostname}
  </record>
</filter>
```
but it does not work
```text
[warn]: unknown placeholder `${Socket.gethostname}` found
```
If I have understood correctly, solution is adding "enable_ruby" before record tag.

**Comment by kiyoto** [comment]
Indeed. it should be replaced with "#{Socket.gethostname}" (with the double quotes)

Do you think you can submit a PR? Thank you and would love to have you as a contributor!

**Comment by reinerRubin** [comment]
>Do you think you can submit a PR? Thank you and would love to have you as a contributor!
Yeah! I can do it today but little later.
