### ISSUE TITLE
security concern: using configuration file: <ROOT>

### ISSUE THREAD

**Issue by dkavraal** [fluent/fluentd-docs#203]
When starting up the agent, the configuration is dumped into the log. In that log, there are secret keys for the certificates. This is something should be considered once more I guess. Maybe there is an option to dump not the config into log. However it might be default option not to miss.

**Comment by repeatedly** [comment]
Recent fluentd has `secret` parameter to fluentd configuration.
So if you use latest fluentd and updated plugins, sensitive configuration are not logged, e.g. s3 and etc.

> However it might be default option not to miss.

You mean `--suppress-config-dump` should be `true` by default?

**Comment by repeatedly** [comment]
No response. Closed.
