### ISSUE TITLE
"Download doc as PDF" doesn't work.

### ISSUE THREAD

**Issue by safiyat** [fluent/fluentd-docs#205]
I have been facing this issue since some time now.

After clicking `Download doc as PDF`on any doc page, the form to enter the user details or social auth comes up, but no downloads happen after completing any of that.

Please check.

**Comment by kiyoto** [comment]
Thanks for reporting. I am looking at this right now. Stay tuned.

**Comment by kiyoto** [comment]
Sorry, our backend delivery system was misconfigured. This should be fixed now. Please try again.

Thank you for your interest in Fluentd!
