### ISSUE TITLE
out_forward max_retry_wait parameter default value is unclear

### ISSUE THREAD

**Issue by groner** [fluent/fluentd-docs#214]
> The initial and maximum intervals between write retries. **The default values are 1.0 seconds and unset (no limit).** The interval doubles (with +/-12.5% randomness) every retry until max_retry_wait is reached. **In the default configuration the last retry waits for approximately 131072 sec, roughly 36 hours.**

This seems to say that the default for `max_retry_wait` is both unlimited and 36 hours, unless I'm misunderstanding the meaning of  "last retry".

**Comment by repeatedly** [comment]
First sentence says "`max_retry_wait` is maximum intervals between write retries" and second sentence says "unset(no limit)". So it says "retry interval is increasing without limit by default."

Hmm... if this is confusing, suggest better explanation is welcome :)
Should mention `retry_limit` or something?

**Comment by groner** [comment]
But the third sentence says the last retry waits for ... roughly 36 hours.  Since the retry interval increases, I interpreted "last retry waits" to mean `max_retry_wait`.  Is that wrong?

**Comment by repeatedly** [comment]
Hmm.. I see.
I'm not sure what the sentence is best.
If you have a more better idea, could you send a PR?

**Comment by fujimotos** [comment]
I know this is a quite old topic, but I think I have found the source of the confusion.

As @groner pointed out, it seems to me that the paragraph does not make much sense *per se*. In fact, when I first read it, the following question struck me: "If the maximum interval has no limit by default, why won't it just increase indefinitely?"

The key to resolve this question is in the next paragraph:

> **retry_max_times, retry_forever**
> The limit on the number of retries before buffered data is discarded, and an option to disable that limit (if true, the value of `retry_max_times` is ignored and there is no limit).  The default values are 17 and false (not disabled). If the limit is reached, buffered data is discarded and the retry interval is reset to its initial value (`retry_wait`).

So, by default, there is a limit on the number of retries (17 times), and obviously this is where the "131072 sec" limit comes from (= `2^17`). In this context, the original paragraph makes perfect sense; In short, it just describes how long the sleep interval would be after17 retries.

We can prevent such confusion by making the context above a little more explicit.
Here is my attempt to fix it: #403

What do you guys think about this patch? If there's no objection, I'll merge it.

**Comment by fujimotos** [comment]
@repeatedly @groner 
I'll merge the patch above (#403) later today.

**Comment by fujimotos** [comment]
The pull request #403 got closed.
So I close this issue, too.
