### ISSUE TITLE
Application Error for fluentular.herokuapp.com

### ISSUE THREAD

**Issue by hayesr** [fluent/fluentd-docs#218]
[This page](http://docs.fluentd.org/articles/parser-plugin-overview) references Fluentular, but that app appears to be down.

**Comment by repeatedly** [comment]
It is a heroku limitation: https://groups.google.com/d/msg/fluentd/m43MkU1R7rg/L7n51LVyBQAJ
I will update the document and mention [fluentd-ui editor](http://docs.fluentd.org/articles/fluentd-ui#intail-setting) for regexp testing.
