### ISSUE TITLE
Incomplete buffer documentation

### ISSUE THREAD

**Issue by bayetovsky** [fluent/fluentd-docs#222]
Greetings,

This is a minor issue with the documentation but currently there is only information on how to use "retry_wait" parameter and no data regarding:
- max_retry_wait (what are valid values?);
- retry_limit (what are valid values?);
- disable_retry_limit (assume it's boolean values due to buffer overview);

Even though they are mentioned in the buffer overview, there's no examples and no list of valid values to be input in each of them.

**Comment by repeatedly** [comment]
http://docs.fluentd.org/articles/buffer-plugin-overview#buffer-structure

This section has example configuation like below.

```aconf
<match pattern>
  buffer_type memory
  buffer_chunk_limit 256m
  buffer_queue_limit 128
  flush_interval 60s
  disable_retry_limit false
  retry_limit 17
  retry_wait 1s
</match>
```

Is this not enough?

**Comment by repeatedly** [comment]
Ah, max_retry_wait is missing.

**Comment by bayetovsky** [comment]
Actually had missed that example block (mainly cause I was looking for max_retry_wait) but yeah I guess that would be enough :+1:

Adding "max_retry_wait" to the time unit explanation would also be a plus

**Comment by repeatedly** [comment]
I will add it later. Thanks for the report.
