### ISSUE TITLE
fluent/supervisor.rb:184:rescue in dry_run: dry run failed: Permission denied @ rb_sysopen - /home/kpm/public_html/bq_scheme/impression_v1.json

### ISSUE THREAD

**Issue by kpmbro** [fluent/fluentd-docs#223]
hi,
I keep getting this error , try chmod 777 . 0644 and chown for the user , root , td-agent .. still no luck. is there any tip for this matter ? 
thanks

**Comment by repeatedly** [comment]
It seems bq plugin issue.

**Comment by repeatedly** [comment]
Wait. This error happens on only dry-run mode?

**Comment by kpmbro** [comment]
Happens in td-agent restart, this is the error

Best Regards , Amir Manan

**Comment by repeatedly** [comment]
Hmm... could you post this issue on fluent-plugin-bigquery?
I'm not faimilar with bigquery plugin so I can't judge this problem happens with other plugin or not.
