### ISSUE TITLE
Include --dry-run flag in configuration documentation

### ISSUE THREAD

**Issue by aatkinson-canopy** [fluent/fluentd-docs#232]
Hey,

Please include info and an example on the fluentd --dry-run flag in the config docs here:
http://docs.fluentd.org/articles/config-file

fluentd --dry-run -c /path/to/td-agent.conf 

Best,
Alex

**Comment by repeatedly** [comment]
Hmm... --dry-run is not configuration file format or parameter
but putting `Check configuration` like section seems better.
I will update it.

**Comment by repeatedly** [comment]
Added
