### ISSUE TITLE
Doesn't able to click link in http://docs.fluentd.org/articles/

### ISSUE THREAD

**Issue by wejick** [fluent/fluentd-docs#236]
Hello,

I'm not really sure here is the right place to report this issue. For some reason I don't know I couldn't click (left click) any link in [http://docs.fluentd.org/articles/config-file](http://docs.fluentd.org/articles/config-file) . However the right click and middle click is working.

edit :
This is the error from browser console : 

```
Error: Origin is not allowed by Access-Control-Allow-Origin
Stack trace:
</h.prototype.crossDomainError@https://s3.amazonaws.com/td-cdn/sdk/td-1.2.0.js:4:2460
</h.prototype.end/i.onreadystatechange@https://s3.amazonaws.com/td-cdn/sdk/td-1.2.0.js:4:3007
1config-file:1425:79
```

**Comment by repeatedly** [comment]
Thansk for the report.

@kiyoto Do you know the reason? Does td change SDK behaivour?

**Comment by MiLk** [comment]
I have the same issue with Adblock plus enabled.
If I disable it, it works fine.

**Comment by okkez** [comment]
It works fine now. We can close this issue.

**Comment by fujimotos** [comment]
Closed.
