### ISSUE TITLE
A complete removal process for td-agent/fluentd should be added to docs

### ISSUE THREAD

**Issue by alanyee** [fluent/fluentd-docs#240]
`yum remove td-agent` does remove some things, but other things still remained such as `vim /etc/td-agent/td-agent.conf`. 

The docs use terms such as "install" and "uninstall" but those terms should link to a page about installation (which exits) and a page about uninstallation (which I cannot find).

**Comment by repeatedly** [comment]
> other things still remained such as vim /etc/td-agent/td-agent.conf.

Hmm... this is `yum` manner. `apt-get` has `remove` and `purage` but `yum` doesn't have `purge` like command.
Do you think we should write these each command manner in fluentd-docs?

**Comment by repeatedly** [comment]
No response.
