### ISSUE TITLE
BufferQueueLimitError error="queue size exceeds limit

### ISSUE THREAD

**Issue by SowmyaNayan** [fluent/fluentd-docs#244]
Hi,

We are using fluentd -kafka plugin and default buffer chunk and queue size. 

Other variable set are below.
   flush_interval - 2s
    disable_retry_limit - false
    retry_limit - 3
    retry_wait - 2s

The application works fine for a QPS - 500 and Message size-10KB running for a duration of 5min.
Total message consumed = 500 * 120 = 60000.

But with the same QPS and size , when run continuously for 10min, **BufferQueueLimitError error="queue size exceeds limit**  is shown , and only 230000 messages are consumed instead of 300000.

Ideally if the the message are flushed , then the buffer limit should not occur in this scenario. Not sure why this fails. What is the right way set the buffer configuration?
Please guide

Thanks
Sowmya

**Comment by repeatedly** [comment]
This is documentation repository and don't use issue for questions.
https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
