### ISSUE TITLE
Can't start td-agent on Centos 7

### ISSUE THREAD

**Issue by triethuynh92** [fluent/fluentd-docs#251]
Hi all,
I have installed td-agent follow http://docs.fluentd.org/articles/install-by-rpm. But when I strat service, it didn't work and has logs:

[root@localhost ~]# systemctl status td-agent -l
● td-agent.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/rc.d/init.d/td-agent; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2016-12-20 17:45:36 ICT; 2min 13s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3542 ExecStart=/etc/rc.d/init.d/td-agent start (code=exited, status=1/FAILURE)
   Memory: 1.5M

Dec 20 17:45:35 localhost.localdomain td-agent[3542]: 2016-12-20 17:45:35 +0700 [error]: fluent/supervisor.rb:338:fork: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/bin/fluentd:5:in `<top (required)>'
Dec 20 17:45:35 localhost.localdomain td-agent[3542]: 2016-12-20 17:45:35 +0700 [error]: fluent/supervisor.rb:338:fork: /opt/td-agent/embedded/bin/fluentd:23:in `load'
Dec 20 17:45:35 localhost.localdomain td-agent[3542]: 2016-12-20 17:45:35 +0700 [error]: fluent/supervisor.rb:338:fork: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
Dec 20 17:45:35 localhost.localdomain td-agent[3542]: 2016-12-20 17:45:35 +0700 [error]: fluent/supervisor.rb:338:fork: /usr/sbin/td-agent:7:in `load'
Dec 20 17:45:35 localhost.localdomain td-agent[3542]: 2016-12-20 17:45:35 +0700 [error]: fluent/supervisor.rb:338:fork: /usr/sbin/td-agent:7:in `<main>'
Dec 20 17:45:36 localhost.localdomain td-agent[3542]: [25B blob data]
Dec 20 17:45:36 localhost.localdomain systemd[1]: td-agent.service: control process exited, code=exited status=1
Dec 20 17:45:36 localhost.localdomain systemd[1]: Failed to start LSB: data collector for Treasure Data.
Dec 20 17:45:36 localhost.localdomain systemd[1]: Unit td-agent.service entered failed state.
Dec 20 17:45:36 localhost.localdomain systemd[1]: td-agent.service failed.

What can I do to fix it?

**Comment by repeatedly** [comment]
This is fluentd documentation repository.
if you have a question, use fluentd mailing list instead.
