### ISSUE TITLE
Invisible 'Newsletters' link is clickable

### ISSUE THREAD

**Issue by nokute78** [fluent/fluentd-docs#258]
![sample](https://cloud.githubusercontent.com/assets/16795275/23062878/12e79d6c-f54b-11e6-94f4-ac1704e0afe0.png)

Inside of rectangle is clickable and go to http://www.fluentd.org/newsletter_signup
It seems that `Newsletters` link is invisible but clickable.
In this case, `out_file` link is overlapped that newsletter link.

The environment I can reproduce is

* Windows7 64bit + Firefox 51.0.1
* Windows7 64bit + Chrome 56.0.2924.87
* CentOS 6.8 + Firefox 45.7.0

**Comment by fujimotos** [comment]
Sorry for a late reply.

The issue you reported is fixed by the pull requet #396.
As this patch got merged to the master branch a short while ago,
this "clickable-invisible-popups" issue must be resolved by now.

Thanks for reporting the issue. It was really a lot of help.
