### ISSUE TITLE
Step 4 Install by msi  Fluentd Window Service missing

### ISSUE THREAD

**Issue by zjesse713** [fluent/fluentd-docs#259]
Control Panel -> System and Security -> Administrative Tools -> Services, and you’ll see Fluentd Windows Service is listed.

Fluentd Windows Service is not listed. 

 Is this step mandatory?

**Comment by repeatedly** [comment]
> Fluentd Windows Service is not listed.

This is our previous result: ![Windows Service Example](https://qiita-image-store.s3.amazonaws.com/0/31816/0fa22bb3-c099-21ea-def6-fbf72dd14784.jpeg)
If your fluentd registration is succeeded without any problem, you can see above service.

**Comment by zjesse713** [comment]
I followed all the steps, even step 3. running the 2 commands on td-agent command prompt. Fluent Windows Service still missing

**Comment by zjesse713** [comment]
Okay, I had to run td-agent command prompt as admin. It works now Thank you.
