### ISSUE TITLE
Link to GitHub DaemonSet Configuration broken on Kubernetes page

### ISSUE THREAD

**Issue by adamjerickson** [fluent/fluentd-docs#263]
Page:
http://docs.fluentd.org/v0.12/articles/kubernetes-fluentd

Link Text:
DaemonSet Configuration

Link href:
https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/conf

Result:
404 from GitHub

Expected Result:
Page loads

**Comment by repeatedly** [comment]
@edsiper Could you handle this? Currently, fluentd-kubernetes-daemonset has several preset configuration. So I think need to modify several sentence.

**Comment by repeatedly** [comment]
I just fixed broken links.
