### ISSUE TITLE
Plugin Development->Installing custom plugins path is incorrect for version 0.12

### ISSUE THREAD

**Issue by compucandi** [fluent/fluentd-docs#264]
The plugin development article, http://docs.fluentd.org/v0.12/articles/plugin-development , contains this verbiage under Installing custom plugins:  "To install a plugin, please put the ruby script in the /etc/fluent/plugin directory".  For version 0.12 (at least what I installed via rpm for Centos), the path for plugins is: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems .  The directory /etc/fluent does not exist, but /etc/td-agent/plugin does exist, but is empty.  Plugins are located here, at least in my version:  /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/<plugin name>

Please correct, or clarify (if the differentiator is a custom plugin, or td-agent), this documentation with the path information.

**Comment by repeatedly** [comment]
Above link is for plugin development, not production deployment.
For deployment case, http://docs.fluentd.org/v0.12/articles/plugin-management this article describes pluign management.

**Comment by compucandi** [comment]
Thanks for the clarification!  My plugin is working now!
