### ISSUE TITLE
document the `reserve_time` parameter

### ISSUE THREAD

**Issue by slang800** [fluent/fluentd-docs#276]
`reserve_time` is a configuration parameter used in a [couple places in the codebase](https://github.com/fluent/fluentd/search?utf8=%E2%9C%93&q=reserve_time&type=), but I can't find it in the documentation. It's not a particularly confusing parameter, but when I was looking for something to prevent the time field from being overwritten after using `rewrite_tag_filter`, I couldn't find it in the parser docs & had to dig for it in the codebase.

moved from https://github.com/fluent/fluentd/issues/1591

**Comment by repeatedly** [comment]
>  I couldn't find it in the parser docs

because this parameter is used in filter_parser, not parser itself.
I just added filter_parser document to v0.14 content.
