### ISSUE TITLE
HELP: Format needed for nginx ingress logs

### ISSUE THREAD

**Issue by shavo007** [fluent/fluentd-docs#313]
Hi,

I have created an issue here for kubernetes nginx ingress:
https://github.com/kubernetes/ingress-nginx/issues/1664

It has its own log format:
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/log-format.md

I have tried to use nginx parser but I dont believe it works:

```

  extra.conf: |
    # Example filter that adds an extra field "cluster_name" to all log
    # messages:
    # <filter **>
    #   @type record_transformer
    #   <record>
    #     cluster_name "your_cluster_name"
    #   </record>
    # </filter>
      <filter kube.ingress-nginx.nginx-ingress-controller>
        @type parser
        # Fluentd provides a few built-in formats for popular and common formats such as "apache" and "json".
        format nginx
        key_name log
        # Retain the original "log" field after parsing out the data.
        reserve_data true

        # The access logs and error logs are interleaved with each other and have
        # different formats, so ignore parse errors, as they're expected
        suppress_parse_error_log true
      </filter>

```

Anyone!?

Thanks,
Shane.

**Comment by fujimotos** [comment]
I checked kubernetes/ingress-nginx#1664, and it seems that the problem had been resolved there.
In fact, the closs-posted issue has been marked as closed weeks ago.

So I close this issue, too.
