### ISSUE TITLE
Creating multiple directories

### ISSUE THREAD

**Issue by peixiaoqing** [fluent/fluentd-docs#405]
Hello: I now have a requirement, three test servers, such as: test1, test2, test3
Now I want test1 to send all its application logs to test2's tdagent, then different application logs are placed in different two files instead of all in td-agent's log files. Then, by sending these logs to the elasticsearch on the top of the test3 through the test2, a centralized display is performed, and test2 is just a management log. After looking at the information, it seems that there is no such method, I would like to do this, how do you need to do it?

**Comment by fujimotos** [comment]
Sorry, but this is not really a place for user support.
There is [a user support forum for fluentd](https://groups.google.com/forum/#!forum/fluentd), so you should ask questions there instead.
......

That said, my psychic powers tell me that what you want to do might be something like this:

 1. Add host signatures into event tags (like `my.app.server1`)
 2. Use "out_forward" to transfer logs from test1 to test2.
 3. Use "out_file" to output logs in test2.
    * To handle each log source separately, use match blocks like `<match my.app.server1>`
 4. Use "out_forward" to transfer logs from test2 to test3.
    * To handle all logs uniformly, use a match block with wildcard like `<match my.app.*>`

The following resources will help you:

 - For step 1: https://www.fluentd.org/guides/recipes/apache-add-hostname
 - For step 3: https://docs.fluentd.org/v1.0/articles/out_file
 - For step 2 and 4: https://docs.fluentd.org/v1.0/articles/out_forward
 
For further questions, please ask on the forum I mentioned above.

**Comment by fujimotos** [comment]
I will close this issue...
