### ISSUE TITLE
little confused with instructions

### ISSUE THREAD

**Issue by elinshu** [fluent/fluentd-docs#406]
guide for windows : https://docs.fluentd.org/v1.0/articles/install-by-msi

1. why it write full path on description part, skipped-path on command line? 
I'm not used to commands so I misunderstood it work like '/s' or the other commands...
Step2: Run td-agent from Command Prompt
First, please prepare your config file located at **C:/opt/td-agent/etc/td-agent/td-agent.conf**.
In the prompt, please execute the command below to launch td-agent process.
**fluentd -c conf\td-agent.conf**

2. Is it sample command?
Step5: Install Plugins 
**fluent-gem install fluent-plugin-xyz --version=1.2.3**

**Comment by fujimotos** [comment]
> why it write full path on description part, skipped-path on command line?

As far as I can tell, that's just a command-usage example, and there is no particular difference whether you use a relative path or an absolute path.

In fact, you can just use an absolute path in the command line as below:

```cmd
> fluentd -c C:\opt\td-agent\etc\td-agent\td-agent.conf
```

It should work either way as long as the configuration file does exist on the specified path.

> Is it sample command?

Yes. There is no such a plugin named "fluent-plugin-xyz", so you are supposed to replace it with one you actually want to install (like "fluent-plugin-mail").

**Comment by fujimotos** [comment]
Also, if you have further questions about general usage on Windows system, please ask on [the user support group for fluentd](https://groups.google.com/forum/#!forum/fluentd).

Because this issue tracker is not intended to be a support forum, you should get much much better responses/answers there.

**Comment by fujimotos** [comment]
I'll close this issue. Please reopen it if you have any other questions.
