### ISSUE TITLE
Dev Note: Improve the documentations  in "Use Cases"

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluentd-docs#413]
This issue briefly describes the plan to improve the [Use Case](https://docs.fluentd.org/v1.0/categories/logging-from-apps) section of the documentation.

The following memo is purely informational; It should provides the context behind the changes which will take place in the next few days (or weeks).

### Improvement 1: Upgrade v0.12 articles to v1.0

A number of articles in this section are not yet migrated to v1.0, including:

 - ["How To Filter Or Modify Data Inside Fluentd (Apache as an Example)"](https://docs.fluentd.org/v0.12/articles/filter-modify-apache)
 - ["Store Apache Logs into Riak"](https://docs.fluentd.org/v0.12/articles/apache-to-riak)
 - ["Collecting GlusterFS Logs with Fluentd"](https://docs.fluentd.org/v0.12/articles/collect-glusterfs-logs)

As a starter, I will upgrade these instructions, and make sure they actually work with td-agent3. As this task requires setting up a working RIak/GlusterFS environment, it will took (at least) several days.

In this process, maybe I can salvage the orphaned pull request: #233

### Improvement 2: Clean up the categories

The current categorization seems somewhat krudgy to me. For example, [the article on MongoDB](https://docs.fluentd.org/v0.12/articles/apache-to-mongodb) is currently listed in the "Data Analytics" section, while [the article on Riak](https://docs.fluentd.org/v0.12/articles/apache-to-riak) resides in another section ("Data Archiving").

I think a better perspective will be provided by grouping related articles together and use more descriptive category titles as below:

    Use Cases
     |
     +- Data Analytics
     |   |
     |   +- Data Analytics with Treasure Data
     |   |
     |   +- Data Collection to Hadoop (HDFS)
     |   |
     |   +- Collecting GlusterFS Logs
     |
     +- Connecting to Data Storages
         |
         +- Store Apache Logs into Amazon S3
         |
         +- Store Apache Logs into Riak
         |
         +- Store Apache Logs into MongoDB
         |
         +- Store Apache Logs into Minio

**Comment by cosmo0920** [comment]
Riak is no longer maintained.
see: https://www.theregister.co.uk/2017/07/31/end_of_the_road_for_basho_as_court_puts_biz_into_receivership/

**Comment by fujimotos** [comment]
> Riak is no longer maintained.

Riak has a good chance to survive, if enough people care about the product.

That being said, `fluent-plugin-riak` has not been maintained for more than 3 years,
and I can confirm it does not work with Fluentd v1.0 right now. Also, as to
`fluentd-plugin-gracier`, the last update was in 2012.

This leads me to the conclusion that there is quite little interest in maintaining
these connector plugins, and we can hardly rationalize the effort of porting the
following articles to Fluentd v1.0:

 - ["Store Apache Logs into Riak"](https://docs.fluentd.org/v0.12/articles/apache-to-riak)
 - ["Collecting GlusterFS Logs with Fluentd"](https://docs.fluentd.org/v0.12/articles/collect-glusterfs-logs)

So, as opposed to the initial plan, I won't adapt these articles to Fluentd v1.0
and will just leave them as they are.

**Comment by fujimotos** [comment]
OK. Now I've finished the following tasks:

* #418: Migrate the article "Easy Data Stream Manipulation using Fluentd" to v1.0.
* #420: Salvage the unmerged article Store Apache Logs into Minio.
* #421: Clean up the categories in the "Use Cases" section.

I'll close this ticket as resolved.
