### ISSUE TITLE
Thread helper 'helpers :threads' should be 'helpers :thread'

### ISSUE THREAD

**Issue by kvitali** [fluent/fluentd-docs#416]
On https://docs.fluentd.org/v1.0/articles/api-plugin-helper-thread webpage about Thread plugin helper there is an error.
helpers :threads -> FAILS
should be
helpers :thread -> OK

**Comment by fujimotos** [comment]
Thanks for reporting!

I can reproduce the issue with fluentd v1.0.2, and confirm that your
suggestion actually fixes the issue.

I created a pull request containing the fix (#417). As this PR has
been merged minutes ago, the issue should be resolved by now.
