### ISSUE TITLE
Link to Performance Tuning (Multi-Process) page not working in v1.0

### ISSUE THREAD

**Issue by jpaulodit** [fluent/fluentd-docs#428]
I am reading this page, https://docs.fluentd.org/v1.0/articles/performance-tuning-single-process
and when I click on "Performance Tuning (Multi-Process)", the page does not exist.

**Comment by kzk** [comment]
I'm in the process of writing for v1.0. Will be available in a couple of weeks. Yes it's better to fix the dead link for now.

**Comment by fujimotos** [comment]
OK. Now the broken link is band-aided by #428.
As for a real fix, we need to wait the new documentation lands on.

For the time being before the new doc arrives, I think the following page will help:
(for users interested in multi-process optimization)

* https://www.fluentd.org/blog/fluentd-v0.14.15-has-been-released
* https://www.fluentd.org/blog/fluentd-v0.14.12-has-been-released

I also included a link to the release note (v0.14.15) into the current article:

* https://docs.fluentd.org/v1.0/articles/performance-tuning-single-process#multi-workers

This is kinda kludgy, but will help interested users for now.
