### ISSUE TITLE
Milliseconds still not showing with fluentd version 1.1.0

### ISSUE THREAD

**Issue by reubentonna** [fluent/fluentd-docs#434]
We have tried both output as "@type file" and "@type stdout".  Milliseconds are omitted altogether for type file and show up as zeros for type stdout.  The latter case is contrary to your sample here https://docs.fluentd.org/v1.0/articles/out_stdout.

Fluent version reported by "fluentd --version" is fluentd 1.1.0

This problem practically makes fluentd unusable as at least millisecond granularity is a must.  We have observed this problem also last year with an earlier version.

We would appreciate feedback as to whether this problem will be resolved and when, as otherwise we will have to use a different collector.

Our fluent.conf is reproduced below:
```
<source>
  @type  forward
  @id    input1
  @label @mainstream
  port  24224
</source>

<filter **>
  @type stdout
</filter>

<label @mainstream>
  <match stdout.**>
        @type stdout
  </match>
  <match test.**>
    @type file
    @id   output_test1
    path         /fluentd/log/test.*.log
    symlink_path /fluentd/log/test.log
    append       true
    time_slice_format %Y%m%d
    time_slice_wait   1m
    time_format       %Y-%m-%dT%H:%M:%S.%L%z
  </match>
</label>
```

when send an event with fluent-cat as follows:

```
echo '{"message":"hello"}' | fluent-cat -p24224 -h<our host> stdout.log
```

the log is printed as:

```
2018-01-29 12:38:18.000000000 +0000 stdout.log: {"message":"hello"}
```

similarly sending a log event with fluent-cat as follows:

```
echo '{"message":"hello"}' | fluent-cat -p24224 -h<our host> test.log
```

the log is printed as:

```
2018-01-29T12:44:28+00:00       test.log        {"message":"hello"}
```

**Comment by fujimotos** [comment]
I failed to reproduce the issue you reported. In fact, I *can* output
logs with sub-second precision timestamps like below (with Fluentd v1.1.0).

    2018-01-30 12:41:08.122157931 +0900 stdout.log: {"foo":"bar"}

My best guess is that your `fluent-cat` does not work correctly and is
emitting events without a sub-second precision part in the first place.

So please execute `fluent-cat` without any options and arguments:

    $ fluent-cat
    Usage: fluent-cat [options] <tag>
    -p, --port PORT                  fluent tcp port (default: 24224)
    -h, --host HOST                  fluent host (default: 127.0.0.1)
    ...
        --time-as-integer            Send time as integer for v0.12 or earlier

If you don't see the "--time-as-integer" option in the help text, you're
using old `fluent-cat` command.

**Comment by reubentonna** [comment]
Indeed that was it. Thanks for providing feedback and taking the time to reply.

Issue can be considered closed.

**Comment by fujimotos** [comment]
FWIW, your settings for `out_file` will produce logs with second-precision
timestamps. If you want millisecond precision there, you'll need something
like below in your configuration:

```xml
<label @mainstream>
  .....
  <match test.**>
    @type file
    @id   output_test1
    path         /tmp/log/test.*.log
    symlink_path /tmp/log/test.log
    append       true
    <buffer>
      timekey 1d
      timekey_wait 1m
    </buffer>
    <format>
      time_format %Y-%m-%dT%H:%M:%S.%L%z
    </format>
  </match>
</label>
```

**Comment by reubentonna** [comment]
Splendid. Thanks.
