### ISSUE TITLE
Docs:  Typo under 'in_tail', enable_watch_timer

### ISSUE THREAD

**Issue by cwbuege** [fluent/fluentd-docs#435]
The documentation under 'in_tail' at URL "https://docs.fluentd.org/v1.0/articles/in_tail" shows in the chart that 'enable_watch_timer' has a default of 'false', but the paragraph right underneath it says that the default is true:  Enable the additional watch timer. Setting this parameter to false will significantly reduce CPU and I/O consumption when tailing a large number of files on systems with inotify support. The default is true which results in an additional 1 second timer being used.

**Comment by fujimotos** [comment]
Thanks for the feedback. As I inspect the implementation, the option was in
fact `true` by default.

I've pushed a fix a minute ago (#436), so the issue should be resolved by now.
