### ISSUE TITLE
Doc Errata: host and port ignored sentence under wrong section?

### ISSUE THREAD

**Issue by HariSekhon** [fluent/fluentd-docs#452]
Hi

I think there is a misplaced sentence in the following doc:

https://docs.fluentd.org/v1.0/articles/out_elasticsearch

The sentence

```
If you specify this option, host and port options are ignored.

```
appears under the ```user, password, path, scheme, ssl_verify (optional)``` section whereas I believe it should be in the section above ```hosts (optional)```

**Comment by fujimotos** [comment]
Thanks for the issue report!

I submitted a pull request to fix this issue: #453
As this PR has been merged minutes ago, this issue should be resolved by now!
