### ISSUE TITLE
Nginx parser fails to parse default nginx format

### ISSUE THREAD

**Issue by yaron-idan** [fluent/fluentd-docs#471]
When trying to parse a default nginx log, the parser fails because it lacks the last field in the log (`"$http_x_forwarded_for"`)
This can be fix by removing this field from nginx.conf, but I think a more appropriate solution would be to add this field to the regexp. WDYT?

Reproducing the issue can be easily done by launching fluentd and sending a log line from nginx:latest docker image.

**Comment by fujimotos** [comment]
I think I can close this ticket, since #1932 has been merged.
