### ISSUE TITLE
monitor use prometheus doc use wrong version

### ISSUE THREAD

**Issue by tangyouze** [fluent/fluentd-docs#472]
In the page https://docs.fluentd.org/v1.0/articles/monitoring-prometheus it docs that 
```
fluent-gem install fluent-plugin-prometheus --version=0.4.0
```
however fluentd v1.0 requires  fluent-plugin-prometheus 1.x.x to work, this should be fixed.

**Comment by fujimotos** [comment]
@tangyouze Thanks for the feedback!
I've just updated the article to use fluentd-plugin-prometheus v1 (#486).
