### ISSUE TITLE
fluentd都会存在删除正在使用的文件，空间不释放的问题

### ISSUE THREAD

**Issue by fengyingjie2018** [fluent/fluentd-docs#480]
fluentd都会存在删除正在使用的文件，空间不释放的问题,采用脚本定时删除回滚后的日志文件的方式减少日志对系统盘的占有；这样肯定会出现某一个时刻这个acess.log刚刚回滚完产生一个旧文件acessold.log就执行定时任务脚本把这个文件给从磁盘上删除，那么如果这个旧文件acessold.log没有读完fluentd就会不关闭文件句柄，导致这个句柄空间不释放的问题（可以通过sudo lsof|grep deleted |grep fluentd方式查看）,一旦这个没有释放的空间积累量较大时候系统盘会被占满影响其他服务

**Comment by cosmo0920** [comment]
请将此问题报告到[fluentd问题跟踪](https://github.com/fluent/fluentd/issues)？
这不是fluentd文档问题
