### ISSUE TITLE
[Documentation] Question about stdout

### ISSUE THREAD

**Issue by ecristea** [fluent/fluentd-docs#505]
In [stdout](https://docs.fluentd.org/v1.0/articles/out_stdout) the 2nd Note on the page reads:
```
The first part shows the output time, not the time attribute of message event
structure as out_stdout does.
```
This page is about `out_stdout`, should this `Note` be removed?

**Comment by fujimotos** [comment]
> This page is about out_stdout, should this Note be removed?

Thanks. It's evidently misplaced.

I have removed the note by the pull request #506, so the issue should be fixed by now.
