### ISSUE TITLE
parser_json: keep_time_key parameter for v1.0

### ISSUE THREAD

**Issue by ecristea** [fluent/fluentd-docs#507]
Hi,

It is correct to assume `keep_time_key` parameter is still supported in `parser_json` v1.0?
(The `keep_time_key` parameter it is documented in [v0.12,](https://docs.fluentd.org/v0.12/articles/parser_json) and it is not mentioned in [v1.0)](https://docs.fluentd.org/v1.0/articles/parser_json))

Based on attached example it seems that `keep_time_key` it is respected when
sending a single json event and not respected when sending same json event as an array.
I attached two data samples with following content:
`{"foo":"bar", "time": 1523692120}`
`[{"foo":"bar", "time": 1523692120}]`

When feeding 1st event fluentd keeps the time field in the record.
`2018-04-14 07:48:40.000000000 +0000 app.log: {"foo":"bar","time":1523692120}`

However, when using 2nd event fluentd removes the time field from the record.
`2018-04-14 07:48:40.000000000 +0000 app.log: {"foo":"bar"}`

Is this expected?
What configuration should be used to keep the time field in the (fluentd) record?

If it helps, (if docker, docker-compose available) flume can be started with
docker (`./runWithDocker.sh`) or docker-compose (`docker-compose up`) and events can be sent using `./sendEvent.sh`.

[fluent_parser_json_keep_time_key.tar.gz](https://github.com/fluent/fluentd-docs/files/2068075/fluent_parser_json_keep_time_key.tar.gz)

**Comment by fujimotos** [comment]
> It is correct to assume keep_time_key parameter is still supported in parser_json v1.0?
> (The keep_time_key parameter it is documented in v0.12, and it is not mentioned in v1.0))

Yes it is supported in v1.0 too.  The parameter definitions have been moved to [the other part
of the documentation](https://docs.fluentd.org/v1.0/articles/parse-section#time-parameters) so please read the article for details of the available parameters.

> What configuration should be used to keep the time field in the (fluentd) record?

There is no parameter available to modify the behaviour for now.

If you want an option to configure it, please submit an issue to the main project [fluent/fluentd](https://github.com/fluent/fluentd).

**Comment by ecristea** [comment]
thank you, 
this can be closed

**Comment by fujimotos** [comment]
FYI I have submitted a patch to address the issue reported by you.

Follow fluent/fluentd#2020 for details...
