### ISSUE TITLE
Frustrating typo in example

### ISSUE THREAD

**Issue by MartinVUALTO** [fluent/fluentd-docs#513]
[plugin-version-management](https://docs.fluentd.org/v0.12/articles/plugin-management#plugin-version-management)

The line in error is:

    gem install fluent-plugin-elasitcsearch -v 1.9.3

Note the spelling of *elasitc* rather than elastic. As a novice fluentd and gems user this took me some time to spot!

**Comment by repeatedly** [comment]
Deployed fix: https://docs.fluentd.org/v0.12/articles/plugin-management#plugin-version-management
Thanks for the report!
