### ISSUE TITLE
[Buffer] Potential improvement 

### ISSUE THREAD

**Issue by ecristea** [fluent/fluentd-docs#526]
Fluentd v0.14.7 added a new feature Data compression support in buffers and forward plugin, and the release notes contain following information:

> Fluentd compresses events before writing these into buffer chunk, and extract these data before passing these to output plugins

[Reference](https://www.fluentd.org/blog/fluentd-v0.14.7-has-been-released)

If this is still valid IMHO will be worth to add this sentence for the [compress](https://docs.fluentd.org/v1.0/articles/buffer-section#buffering-parameters) buffering parameter

**Comment by fujimotos** [comment]
> If this is still valid IMHO will be worth to add this sentence for the compress buffering parameter

@ecristea  My understanding is that compressed chunks are decompressed *if the
output plugin does not support compressed data transfer*.

For example, if you use out_forward with `compress: gzip`, these gzip-compressed
chunks are actually send to the output *as is*. So no wasteful round-trip will happen
(like: `gzip -> text -> gzip`).

Is this behaviour what you are referencing? If so, I will add a small note to the section
which explains the behaviour.

**Comment by ecristea** [comment]
@fujimotos 
Yes, I do believe such a note will help.

**Comment by fujimotos** [comment]
I have appended the information to the document in the patch #527.

If you feel anything missing, please feel free to reopen this issue.
