### ISSUE TITLE
Parser plugin page does not show detailed usage examples

### ISSUE THREAD

**Issue by kriston13** [fluent/fluentd-docs#532]
The [Parser plugin overview](http://docs.fluentd.org/v0.12/articles/parser-plugin-overview) page describes how to "use" a plugin, by stating to call it by name.

The given example is:
```
<source>
  @type tail
  path /path/to/input/file
  format my_custom_parser
</source>
```
However, this only uses the default parameters. How would a person then specify the additional parameter configurations?

This is alluded to in the individual parser pages like [CSV](https://docs.fluentd.org/v0.12/articles/parser_csv), or [multiline](https://docs.fluentd.org/v0.12/articles/parser_multiline), but it's not clearly called out. 

I suggest having an example that is broader. Something more like:

```
<source>
  @type tail
  path /path/to/input/file
  format a_parser
  a_parser_configuration configuration
  another_parser_configuration another_configuration
</source>
```

Then with an actual example of something like

```
  @type tail
  path /path/to/file
  format json
  time_key timestamp
  time_format YYYY/MM/DDTHH:mm:ss
```

Thoughts?

**Comment by fujimotos** [comment]
OK. Now I have merged #534.

If you have noticed anything about it, please comment here.
