### ISSUE TITLE
out_splunk logs mention Fluentd Enterprise which doesn't exist

### ISSUE THREAD

**Issue by RohitK89** [fluent/fluentd-docs#550]
https://docs.fluentd.org/v0.12/articles/out_splunk

```The Splunk Enterprise and Splunk Cloud output plugin are available as part of a Fluentd Enterprise subscription - for more information see Fluentd Enterprise .```

**Comment by fujimotos** [comment]
It was fixed by #552. Thanks for pointing it out.
