### ISSUE TITLE
out_mongo_replset: required parameter replica_set is undocumented

### ISSUE THREAD

**Issue by ethankan** [fluent/fluentd-docs#568]
The `replica_set` parameter is required but is not mentioned in the documentation.

The `name` parameter is mentioned but it is not a recognized parameter for this plugin.

**Comment by fujimotos** [comment]
I confirmed the page is now out-of-date.
I will take time this week and update the manual.

**Comment by fujimotos** [comment]
Fixed by #569. Thanks for reporting!
