### ISSUE TITLE
Hello, cannot load Windows event logs

### ISSUE THREAD

**Issue by mimachniak** [fluent/fluentd-docs#572]
When I lunch fluentd with configuration I get this message

0 no patterns matched tag="winevt.raw"

**Comment by cosmo0920** [comment]
Could you share your configuration?

**Comment by cosmo0920** [comment]
You can use `winevt.raw` pattern like the following:

```aconf
<match winevt.raw>
  @type stdout
  @id output_stdout
</match>
```

Otherwise, `winevt.raw` is not handled in your configuration.
Default configuration does not handle `winevt.raw`.

**Comment by fujimotos** [comment]
Apparently this question has been multiposted. So I'll close this one.

 https://github.com/fluent/fluent-plugin-windows-eventlog/issues/12
