### ISSUE TITLE
Add worker section description

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd-docs#574]
This is an advanced usage for Fluentd.
Like https://github.com/fluent/fluentd/issues/2145, users want to use multi workers but there is a few pitfall.
This pitfall is originated from multi worker unsupported plugin implementation.

It can avoid with `<worker >` section but I cannot find `<worker >` section usage documentation.

**Comment by fujimotos** [comment]
OK. I'll write some article on it next week.

**Comment by repeatedly** [comment]
I have just added multi process workers article.
If you have an idea for document improvement, please send a patch :)

**Comment by fujimotos** [comment]
That's awesome. Thank you!
