### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by npappin-wsu** [fluent/fluentd-docs#576]
[Installing Fluentd Using rpm Package](https://docs.fluentd.org/v1.0/articles/install-by-rpm#amazon-linux)

The above documentation for amazon-linux seems to be outdated. When the script is used for amazon linux 2 it errors out saying it cant find the file.

**Comment by repeatedly** [comment]
> When the script is used for amazon linux 2 it errors out saying it cant find the file.

That's weird. The file exists correctly.

https://td-agent-package-browser.herokuapp.com/3/amazon/2/2/x86_64

**Comment by npappin-wsu** [comment]
Terribly sorry it seems we had the redhat version and that was what was causing the error.

I will go ahead an close this. Thanks for the quick attention.

Nick
