### ISSUE TITLE
API Plugin Test

### ISSUE THREAD

**Issue by harsxv** [fluent/fluentd-docs#577]
Hello.

API Plugin Test page seems to be not working for a long day.

URL: https://docs.fluentd.org/v1.0/articles/api-plugin-test
Screenshot: https://jmp.sh/MQ5BbbE

**Comment by fujimotos** [comment]
The following might be the page you are looking for:

https://docs.fluentd.org/v1.0/articles/plugin-test-code

Although there are a few links to `api-plugin-test` in doc.fluentd.org,
the page actually never exist in the first place.

I'll clean these dead links up next week.

**Comment by fujimotos** [comment]
Fixed by #578. Thanks for reporting!
