### ISSUE TITLE
docker-compose article uses elasticsearch/kibana images without tag, which fails

### ISSUE THREAD

**Issue by mcgeeco** [fluent/fluentd-docs#600]
For some reason the elasticsearch and kibana docker repos do not support the `latest` tag, and so following the article exactly will not work. A version needs to be specified for each of those docker images. I guess this means pinning to a version for this article, or notifying the reader that they should look up the latest version themselves and append to the image name in the `docker-compose.yml` file.

Thanks for putting together the article by the way, it's really helpful!

Edit: Sorry, I should have included the link: https://docs.fluentd.org/v0.12/articles/docker-logging-efk-compose

Edit 2: I should have noted this was on the v0.12 docs, so apologies if that's meant to be deprecated already. There are a few other small issues as well - the version of the elasticsearch plugin used in the Dockerfile no longer works here (had to update to `1.9.5`) and the index pattern is also incorrect (should be `fluentd-*`). 
Apart from those issues, though the article seems to hold up with `fluentd/fluentd:latest`, so it could be worth updating?

**Comment by fujimotos** [comment]
>  I should have noted this was on the v0.12 docs, so apologies if that's meant to be deprecated already.

Thanks for pointing it out. v0.12 is still supported as of today.

I think I can work on the article to fix these issues up this month,
so please wait a bit.

**Comment by mcgeeco** [comment]
Thanks! Let me know if there's anything I can help with.

**Comment by cosmo0920** [comment]
I've sent a PR to update the efk docker compose document.
Please take a look.
