### ISSUE TITLE
in_unix input source missing from v1 docs

### ISSUE THREAD

**Issue by artash** [fluent/fluentd-docs#608]
`in_unix` input source documentation is missing here https://github.com/fluent/fluentd-docs/tree/master/docs/v1.0 

It is present in v0.12 docs https://github.com/fluent/fluentd-docs/blob/master/docs/v0.12/in_unix.txt

Is the in_unix source being deprecated? There's a commented out log record here https://github.com/fluent/fluentd/blob/v1.3.2/lib/fluent/plugin/in_unix.rb#L187, so it's not clear whether or not this input source is going to be supported in the future versions of fluentd.

**Comment by repeatedly** [comment]
Yes. `in_unix` is still supported but it still use old plugin API...

**Comment by cosmo0920** [comment]
Migrating `in_unix` to use Fluentd v1 API, we should implement unix socket server in server plugin helper.... 
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/server.rb#L180
