### ISSUE TITLE
Close direction of the match directive Typo

### ISSUE THREAD

**Issue by sandats** [fluent/fluentd-docs#621]
The match directive in the URL below is closed with source, but is not it closed with a match?
https://docs.fluentd.org/v1.0/articles/output-plugin-overview

```
<match myservice_name>
  @type file
  path /my/data/access.${tag}.%Y-%m-%d.%H%M.log
  <buffer tag,time>
    @type file
    path /my/buffer/myservice
    timekey     60m
    timekey_wait 1m
  </buffer>
</source>
```

It worked correctly when closed with match.
```
<match myservice_name>
  @type file
  path /my/data/access.${tag}.%Y-%m-%d.%H%M.log
  <buffer tag,time>
    @type file
    path /my/buffer/myservice
    timekey     60m
    timekey_wait 1m
  </buffer>
</match>
```

The explanation of Fluentd v0.12 was similarly closed with source.

**Comment by repeatedly** [comment]
Ah, our mistake. Could you send a patch?

**Comment by sandats** [comment]
Thank you for confirmation.
I will create a patch and send it.
