### ISSUE TITLE
Docker guide has broken commands

### ISSUE THREAD

**Issue by pydo** [fluent/fluentd-docs#628]
**Description**
One of the `docker run` commands in the [docker logging guide](https://www.fluentd.org/guides/recipes/docker-logging) will fail when executed from a bash shell.

**Repo steps**
```
 docker run --log-driver=fluentd ubuntu echo "Hello Fluentd!"
-bash: !": event not found
```

**Solution**
` docker run --log-driver=fluentd ubuntu echo 'Hello Fluentd!'` or  `docker run --log-driver=fluentd ubuntu echo "Hello Fluentd"`

**Notes**
The docker logging link is also broken on the page as it seems to be unmaintained.

**Comment by repeatedly** [comment]
Thanks. Just fixed: https://github.com/fluent/fluentd-website/commit/6925f4f095cf32f2e7a24ce623f1b72e002abcc4
