### ISSUE TITLE
fluent/supervisor.rb:205:rescue in main_process: config error file="/etc/td-agent/td-agent.conf" error="Unknown output plugin 'elasticsearch'. Run 'gem search -rd fluent-plugin' to find plugins"

### ISSUE THREAD

**Issue by sapg** [fluent/fluentd-docs#89]
Even if I do what this error suggests I still get it when trying to start td-agent on CentOS 6.5.

I've installed the gem with `gem install fluent-plugin-elasticsearch` and I've also tried with `fluent-gem install fluent-plugin-elasticsearch`.

Any idea what I'm doing wrong?

**Comment by adamthedeveloper** [comment]
This is actually still happening to me and I think that the link from @repeatedly is dead. Has anyone run into this behavior that can suggest a fix?

**Comment by adamthedeveloper** [comment]
I followed this and got there:

https://github.com/uken/fluent-plugin-elasticsearch/issues/209
